[2025-08-30 23:30:14,590 ] 156 root - INFO - Starting vectorstore pipeline
[2025-08-30 23:30:14,591 ] 62 root - INFO - Loading data from artifacts/data_cleaned.csv
[2025-08-30 23:30:14,643 ] 73 root - INFO - Sample data from artifacts/data_cleaned.csv: [Document(metadata={'source': 'artifacts/data_cleaned.csv', 'row': 0}, page_content=": 0\nBrand Name: C J Enterprise\nProduct Name: Women's Kanjivaram Art Silk Saree Soft Banarasi Style Sari With Blouse Piece For Wedding (Pari122-51)\nRating: 4.0 out of 5 stars\nRating Count: 1,177\nSelling Price: £4.74\nMRP: £9.49\nOffer: (50% off)"), Document(metadata={'source': 'artifacts/data_cleaned.csv', 'row': 1}, page_content=": 1\nBrand Name: SGF11\nProduct Name: Women's Kanjivaram Soft Silk Saree With Blouse Piece\nRating: 3.8 out of 5 stars\nRating Count: 1,806\nSelling Price: £5.67\nMRP: £56.99\nOffer: (90% off)")]
[2025-08-30 23:30:14,643 ] 75 root - INFO - Loaded 937 documents from artifacts/data_cleaned.csv.
[2025-08-30 23:30:14,644 ] 62 root - INFO - Loading data from artifacts/amazon_qa_cleaned.csv
[2025-08-30 23:35:33,924 ] 73 root - INFO - Sample data from artifacts/amazon_qa_cleaned.csv: [Document(metadata={'source': 'artifacts/amazon_qa_cleaned.csv', 'row': 0}, page_content="question: will they fit 2013 f350 dually\nanswer: It's all custom mounting, where there's a will there's a way, don't see why not, figure 15minutes per mud flap, there isn't any hardware included just the stamped sheet metal pieces"), Document(metadata={'source': 'artifacts/amazon_qa_cleaned.csv', 'row': 1}, page_content='question: will they fit 2013 f350 dually\nanswer: You will need to drill another hole in Mud flap & bed frame for added stability.  the added bolt & nut makes it a tighter fit, you only get two existing holes on the bed frame with plastic mud flaps when you bought the truck.  These Dee Zee flaps are much heavier than the plastic/rubber flaps originally provided on truck.')]
[2025-08-30 23:35:33,948 ] 75 root - INFO - Loaded 5416319 documents from artifacts/amazon_qa_cleaned.csv.
[2025-08-30 23:35:34,987 ] 82 root - INFO - Total combined documents: 5417256
[2025-08-30 23:35:35,102 ] 89 root - INFO - Initializing NVIDIA Embeddings.
[2025-08-30 23:35:35,168 ] 95 root - INFO - Embeddings initialized successfully.
[2025-08-30 23:35:35,168 ] 110 root - INFO - Connecting to Pinecone and creating index: ecommerce-chatbot-project
[2025-08-30 23:35:53,831 ] 136 root - INFO - Index status before uploading: {'dimension': 4096,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 8896}},
 'total_vector_count': 8896,
 'vector_type': 'dense'}
[2025-08-31 00:33:00,900 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 00:33:01,545 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE711D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:02,563 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE71A90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:04,587 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE71D10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:08,719 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE71F90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:09,370 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE725D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:10,008 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE72850>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:11,139 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE72AD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:13,172 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE72D50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:17,343 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE72FD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:17,674 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE73610>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:18,212 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE73890>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:19,233 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE73B10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:21,285 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 00:33:21,454 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022FCBE73D90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:21,915 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E058050>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:23,020 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E058550>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:25,176 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E0587D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:25,613 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E0582D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:26,281 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E059090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:26,802 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E059310>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:27,922 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E059590>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:29,206 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E058A50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:30,093 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E059810>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:30,124 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E059E50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:30,699 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05A350>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:31,827 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05A5D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:34,030 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05A850>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:34,095 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05A0D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:34,862 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05B110>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:35,476 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05B390>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:36,510 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05B610>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:38,256 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05AAD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:38,794 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05B890>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:38,931 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002301E05BED0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:39,599 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C54410>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:40,709 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C54690>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:40,806 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 00:33:40,825 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 00:33:41,424 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C54E10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:41,518 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C54B90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:42,501 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C55090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:42,550 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C55310>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:42,825 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C54050>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:42,886 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C54910>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:43,440 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C560D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:43,988 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C56350>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:44,580 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C55590>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:44,646 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C55810>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:45,211 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C565D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:47,058 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C55E50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:47,630 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C56D50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:47,685 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C574D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:48,323 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C57890>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:48,693 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C56AD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:48,813 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C56850>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:48,893 ] 148 root - ERROR - Error creating vector store: HTTPSConnectionPool(host='ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io', port=443): Max retries exceeded with url: /vectors/upsert (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78190>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)"))
[2025-08-31 00:33:48,957 ] 169 root - ERROR - Error in pipeline execution: Error occured in python script [C:\Users\Qadeer\OneDrive\Desktop\1\src\components\vectorstore_builder.py] line number [138] error message [HTTPSConnectionPool(host='ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io', port=443): Max retries exceeded with url: /vectors/upsert (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78190>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)"))]
[2025-08-31 00:33:49,495 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C57B10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:49,495 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78690>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:49,539 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78910>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:50,200 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78E10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:50,300 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C79310>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:51,265 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C79590>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:51,439 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C79810>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:51,698 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C57390>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:51,716 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78A50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:53,472 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C78B90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:53,498 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C79A90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:55,820 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C7A0D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:57,612 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C7A350>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 00:33:57,742 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023015C7A5D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
