[2025-08-31 03:26:28,418 ] 156 root - INFO - Starting vectorstore pipeline
[2025-08-31 03:26:28,419 ] 62 root - INFO - Loading data from artifacts/data_cleaned.csv
[2025-08-31 03:26:28,459 ] 73 root - INFO - Sample data from artifacts/data_cleaned.csv: [Document(metadata={'source': 'artifacts/data_cleaned.csv', 'row': 0}, page_content=": 0\nBrand Name: C J Enterprise\nProduct Name: Women's Kanjivaram Art Silk Saree Soft Banarasi Style Sari With Blouse Piece For Wedding (Pari122-51)\nRating: 4.0 out of 5 stars\nRating Count: 1,177\nSelling Price: £4.74\nMRP: £9.49\nOffer: (50% off)"), Document(metadata={'source': 'artifacts/data_cleaned.csv', 'row': 1}, page_content=": 1\nBrand Name: SGF11\nProduct Name: Women's Kanjivaram Soft Silk Saree With Blouse Piece\nRating: 3.8 out of 5 stars\nRating Count: 1,806\nSelling Price: £5.67\nMRP: £56.99\nOffer: (90% off)")]
[2025-08-31 03:26:28,460 ] 75 root - INFO - Loaded 937 documents from artifacts/data_cleaned.csv.
[2025-08-31 03:26:28,467 ] 62 root - INFO - Loading data from artifacts/amazon_qa_cleaned.csv
[2025-08-31 03:36:28,915 ] 73 root - INFO - Sample data from artifacts/amazon_qa_cleaned.csv: [Document(metadata={'source': 'artifacts/amazon_qa_cleaned.csv', 'row': 0}, page_content="question: will they fit 2013 f350 dually\nanswer: It's all custom mounting, where there's a will there's a way, don't see why not, figure 15minutes per mud flap, there isn't any hardware included just the stamped sheet metal pieces"), Document(metadata={'source': 'artifacts/amazon_qa_cleaned.csv', 'row': 1}, page_content='question: will they fit 2013 f350 dually\nanswer: You will need to drill another hole in Mud flap & bed frame for added stability.  the added bolt & nut makes it a tighter fit, you only get two existing holes on the bed frame with plastic mud flaps when you bought the truck.  These Dee Zee flaps are much heavier than the plastic/rubber flaps originally provided on truck.')]
[2025-08-31 03:36:28,947 ] 75 root - INFO - Loaded 5416319 documents from artifacts/amazon_qa_cleaned.csv.
[2025-08-31 03:36:33,038 ] 82 root - INFO - Total combined documents: 5417256
[2025-08-31 03:36:33,228 ] 89 root - INFO - Initializing NVIDIA Embeddings.
[2025-08-31 03:36:33,384 ] 95 root - INFO - Embeddings initialized successfully.
[2025-08-31 03:36:33,387 ] 110 root - INFO - Connecting to Pinecone and creating index: ecommerce-chatbot-project
[2025-08-31 03:36:48,559 ] 136 root - INFO - Index status before uploading: {'dimension': 4096,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 9472}},
 'total_vector_count': 9472,
 'vector_type': 'dense'}
[2025-08-31 03:51:04,981 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)': /vectors/upsert
[2025-08-31 04:29:47,784 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)': /vectors/upsert
[2025-08-31 04:34:01,853 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)': /vectors/upsert
[2025-08-31 04:45:00,470 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 04:45:01,106 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227ED7BF750>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:02,247 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD0E10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:02,265 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 04:45:02,930 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD1810>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:04,108 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD1A90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:04,282 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD1450>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:06,317 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD1D10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:08,432 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD1F90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:09,133 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD2850>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:09,705 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD2AD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:10,467 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD2210>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:10,885 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD2D50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:11,063 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD3390>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:11,726 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD3890>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:12,941 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD3B10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:12,983 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD34D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:15,156 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000227CCDD3D90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:17,011 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEC050>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:17,741 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEC910>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:18,305 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CECB90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:19,320 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CECE10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:19,337 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEC2D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:19,990 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CED6D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:20,688 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CED950>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:21,519 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CED090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:21,896 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEDBD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:22,105 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io', port=443): Read timed out. (read timeout=None)")': /vectors/upsert
[2025-08-31 04:45:22,687 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEE350>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:23,742 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEE5D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:23,994 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEE0D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:25,582 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEDE50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:25,911 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEE850>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:26,126 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEF110>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:26,676 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEF610>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:26,874 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /vectors/upsert
[2025-08-31 04:45:27,386 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEFB10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:27,914 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEF890>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:28,174 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEEAD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:28,402 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEFD90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:28,717 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF0910>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:29,434 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF0B90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:30,013 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825CEF250>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:30,044 ] 148 root - ERROR - Error creating vector store: HTTPSConnectionPool(host='ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io', port=443): Max retries exceeded with url: /vectors/upsert (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)"))
[2025-08-31 04:45:30,068 ] 169 root - ERROR - Error in pipeline execution: Error occured in python script [C:\Users\Qadeer\OneDrive\Desktop\1\src\components\vectorstore_builder.py] line number [138] error message [HTTPSConnectionPool(host='ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io', port=443): Max retries exceeded with url: /vectors/upsert (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)"))]
[2025-08-31 04:45:30,069 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF0050>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:30,793 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF0E10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:30,794 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF0690>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:31,010 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1A90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:31,617 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1810>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:32,811 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF2210>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:33,002 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1BD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:34,178 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1590>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:34,721 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF2D50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:35,023 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF1E50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:35,069 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF2490>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:35,601 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF2FD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:35,707 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF3890>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:36,350 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF3D90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:36,837 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF39D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:37,203 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF2710>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:37,587 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E8050>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:37,744 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E8910>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:38,460 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E8E10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:38,997 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E82D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:39,285 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825AF3610>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:39,525 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E9090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:39,789 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E8A50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:39,968 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E9A90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:40,561 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EA0D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:41,590 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EA350>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:41,896 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E9950>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:43,084 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E9310>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:43,819 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EA5D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:43,822 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255E9D10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:43,927 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EAE90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:44,665 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EB750>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:44,793 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EB9D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:45,368 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EBED0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:45,731 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EBC50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:46,076 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EA850>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:46,640 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825618190>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:46,801 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825618A50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:47,506 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825618F50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:47,856 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825618410>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:47,903 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228255EB110>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:48,567 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228256191D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:48,685 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825619A90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:48,828 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825618B90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:49,414 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825619F90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:50,507 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561A490>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:50,576 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825619D10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:52,006 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022825619450>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:52,691 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561AFD0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:52,739 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561A710>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:53,065 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561A210>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:53,220 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561B250>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:53,680 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561BD90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:54,347 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F4050>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:54,495 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561BB10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:54,690 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561A990>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:55,044 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F4B90>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:55,481 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F42D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:55,628 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F4E10>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:56,557 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F4550>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:56,771 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F5310>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:56,986 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002282561B4D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:57,693 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F5090>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:45:59,020 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F5810>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:46:00,562 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F5590>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:46:01,939 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F5E50>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
[2025-08-31 04:46:03,148 ] 868 urllib3.connectionpool - WARNING - Retrying (JitterRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228244F60D0>: Failed to resolve 'ecommerce-chatbot-project-z7vz7tk.svc.aped-4627-b74a.pinecone.io' ([Errno 11001] getaddrinfo failed)")': /vectors/upsert
